### ISSUE TITLE
Export return an attribute error

### ISSUE THREAD

**Issue by mattLLVW** [benwilber/honcho-export-systemd#1]
Hi,

It seems that the export does not work.

Here is the traceback:
```
Traceback (most recent call last):
  File "/home/matt/.virtualenvs/project/bin/honcho", line 11, in <module>
    sys.exit(main())
  File "/home/matt/.virtualenvs/project/lib/python3.6/site-packages/honcho/command.py", line 288, in main
    COMMANDS[args.command](args)
  File "/home/matt/.virtualenvs/project/lib/python3.6/site-packages/honcho/command.py", line 107, in command_export
    path = os.path.join(args.location, f.name)
AttributeError: 'tuple' object has no attribute 'name'
```

Would you accept a merge request?

**Comment by mattLLVW** [comment]
@benwilber i'd need this to use it in production, are you willing to accept a merge request?
